spring:
  datasource:
    url: jdbc:mysql://172.21.0.9:3306/dfsp_factory?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: 54fBkUDprEBn72rg
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 1
    maxActive: 20
    minIdle: 3
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    hikari:
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        #        group: dev
        server-addr: http://172.21.32.8:8848/,http://172.21.32.8:8858/,http://172.21.32.8:8868/
        namespace: 39699bc8-4aca-4e37-b183-d247c78b0b26
  jackson:
    time-zone: GMT+8

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sxcoal.dfsp.**.entity
  typeEnumsPackage: com.sxcoal.dfsp.**.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    #    logic-delete-value: 0
    #    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
    #    db-config:
    #      #逻辑删除配置
    #      logic-not-delete-value: 0
    #      logic-delete-value: 1
    #      column-like: true
    refresh: true
    worker-id:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  check-config-location: true

#配置日志级别
logging:
  level:
    com.sxcoal.dfsp.ums: debug
    com.baomidou.mybatisplus: trace
    org.springframework.web: info
    io.swagger.models.parameters.AbstractSerializableParameter: error

# Swagger界面内容配置
swagger:
  enable: true
  title: dfsp-rtsp 监控信息管理 API接口文档
  description: dfsp-rtsp Api 监控信息管理
  version: 1.0.0
  termsOfServiceUrl:
  contact:
    name: YangJinggang
    url:
    email: jinggang.yang@fwenergy.com
server:
  port: 8914

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

feign:
  hystrix:
    enabled: true

#配置请求超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

config:
  #直播流保活时间(分钟)
  keepalive: ${CAMERASERVER_KEEPALIVE:10}
  #nginx推送地址
  push_host: ${CAMERASERVER_PUSH_HOST:qadfsp.fwenergy.cn}
  #额外推送地址
  host_extra: ${CAMERASERVER_HOST_EXTRA:qadfsp.fwenergy.cn}
  #nginx推送端口
  push_port: ${CAMERASERVER_PUSH_PORT:1935}
  #主码流最大码率
  main_code: ${CAMERASERVER_MAIN_CODE:5120}
  #子码流最大码率
  sub_code: ${CAMERASERVER_SUB_CODE:1024}
  #编译版本信息
  version: '@COMMIT_REV@.@BUILD_DATE@'